server:
  port: 8085  # Running Order Service on a separate port

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/courier_aggregator?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: courier_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Using Liquibase for schema changes
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
          jwk-set-uri: http://localhost:8080/oauth2/jwks

  kafka:
    bootstrap-servers: localhost:9092  # Kafka server for event-driven architecture

  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
  liquibase:
    secureParsing: false
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework: INFO
