url=jdbc:mysql://localhost:3306/courier_aggregator?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
username=root
password=root
driver=com.mysql.cj.jdbc.Driver
changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
